image: python:3.7-alpine

before_script:
- apk update
- apk add doxygen
## Uncomment the following line if you use graphviz dot graphs
- apk add graphviz


pages:
  script:
  # doxygen documentation
  - doxygen Doxyfile
  - cp -rf doxygen/vtk_js doxygen/html
  - mv doxygen/html/ public/
  # sphinx manual
  # to use sphinxcontrib-bibtex, the sphinx version must be 1.6.7 or lower
  - pip install sphinx==1.6.7
  - pip install sphinxcontrib-bibtex
  - sphinx-build -b html manual/sphinx/source public/manual
  artifacts:
    paths:
    - public
  only:
  - master

