name: MacOS
on: 
  push:
    branches: master
jobs:
  buildApp:
    name: library
    runs-on: macos-latest
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      - name: install dependence
        run: |
          brew install tcl-tk
          brew install swig
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: info
        run: |
          cmake --version
          g++ --version
      - name: compile library
        run: |
          mkdir Library/build
          cd Library/build
          cmake ..
          make install
          cd ../..
          mkdir libs_OSX
          cp -rf Library/lib libs_OSX/
          cp -rf Library/API libs_OSX/
          cp -rf Library/include libs_OSX/
      - uses: actions/upload-artifact@v2
        with:
          name: libs_OSX
          path: libs_OSX/lib
