name: MacOS
on: 
  push:
    branches: master
jobs:
  buildApp:
    name: library
    runs-on: macos-latest
    env:
      MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      TMP_PWD: hydrothermalfoam
      APPLEDEVELOPERID_APP: ${{ secrets.APPLEDEVELOPERID_APP }}
      QT_DIR: /usr/local/Cellar/qt@5/5.15.2
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      - name: install dependence
        run: |
          brew install tcl-tk
          brew install swig
          brew install libomp
          brew install vtk@8.2
          export LDFLAGS="-L/usr/local/opt/vtk@8.2/lib"
          export CPPFLAGS="-I/usr/local/opt/vtk@8.2/include"
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: info
        run: |
          cmake --version
          g++ --version
      - name: compile library
        run: |
          mkdir Library/build
          cd Library/build
          cmake ..
          make install
          cd ../..
      - name: build command line app
        run: |
          mkdir -p commandline/build
          cd commandline/build
          cmake ..
          make 
      - name: build desktop app
        run: |
          mkdir -p desktop/build
          cd desktop/build
          cmake -DQt5_DIR=${QT_DIR}/lib/cmake/Qt5 -DVTK_DIR=/usr/local/Cellar/vtk@8.2/8.2.0_3/lib/cmake/vtk-8.2 ..
          make 
          ${QT_DIR}/bin/macdeployqt swEOS.app
          echo ${MACOS_CERTIFICATE} | base64 --decode > certificate.p12
          security create-keychain -p ${TMP_PWD} signApp.keychain 
          security default-keychain -s signApp.keychain
          security unlock-keychain -p ${TMP_PWD} signApp.keychain
          security import certificate.p12 -k signApp.keychain -P ${MACOS_CERTIFICATE_PWD} -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${TMP_PWD} signApp.keychain
          codesign --deep -fs "Developer ID Application: ${APPLEDEVELOPERID_APP}" --options=runtime --timestamp swEOS.app
          hdiutil create -srcfolder swEOS.app swEOS.dmg
      - name: package
        run: |
          mkdir libs_OSX
          cp -rf Library/lib libs_OSX/
          cp -rf Library/API libs_OSX/
          cp -rf Library/include libs_OSX/
          cp commandline/build/swEOS libs_OSX/
          cp desktop/build/*.dmg libs_OSX/
      - uses: actions/upload-artifact@v2
        with:
          name: libs_OSX.zip
          path: libs_OSX
      # debug workflow through ssh
      # - uses: actions/checkout@v2
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
