name: Ubuntu
on: 
  push:
    branches: master
jobs:
  buildApp:
    name: library
    runs-on: ubuntu-latest
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      - name: install dependence
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tcl-dev
      - name: info
        run: |
          cmake --version
          g++ --version
          which tclsh
      - name: compile library
        run: |
          mkdir Library/build
          cd Library/build
          cmake -DBuild_API_tcl=OFF ..
          make install
          cd ../..
      - name: build command line app
        run: |
          mkdir -p commandline/build
          cd commandline/build
          cmake ..
          make 
      - name: package
        run: |
          mkdir libs_ubuntu
          cp -rf Library/lib libs_ubuntu/
          cp -rf Library/API libs_ubuntu/
          cp -rf Library/include libs_ubuntu/
      - uses: actions/upload-artifact@v2
        with:
          name: libs_ubuntu.zip
          path: libs_ubuntu
