name: Ubuntu
on: 
  push:
    branches: master
jobs:
  buildApp:
    name: library
    runs-on: ubuntu-latest
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      - name: install dependence
        run: sudo apt-get install tcl
      - name: info
        run: |
          cmake --version
          g++ --version
      - name: compile library
        run: |
          mkdir Library/build
          cd Library/build
          cmake ..
          make install
          cd ../..
          mkdir libs_OSX
          cp -rf Library/lib libs_OSX/
          cp -rf Library/API libs_OSX/
          cp -rf Library/include libs_OSX/
      - uses: actions/upload-artifact@v2
        with:
          name: libs_OSX.zip
          path: libs_OSX
