name: Ubuntu
on: 
  push:
    branches: master
jobs:
  buildApp:
    name: library
    runs-on: ubuntu-latest
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      
      # install QT5
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          dir: '${{ github.workspace }}/QT/'
      
      # install some useful packages 
      - name: install dependence
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tcl-dev

      # set python env
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: info
        run: |
          cmake --version
          g++ --version
          which tclsh
          which python
      
      # cmake library
      - name: build swEOS library
        run: |
          mkdir Library/build
          cd Library/build
          cmake -DBuild_API_tcl=OFF ..
          make install
          cd ../..
      
      # build cmd app
      - name: build swEOS cmd app
        run: |
          mkdir -p commandline/build
          cd commandline/build
          cmake ..
          make 

      # package
      - name: package
        run: |
          mkdir swEOS_ubuntu
          cp -rf Library/lib swEOS_ubuntu/
          cp -rf Library/API swEOS_ubuntu/
          cp -rf Library/include swEOS_ubuntu/
          cp commandline/build/swEOS swEOS_ubuntu/
      
      # debug workflow
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      # upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: swEOS_ubuntu.zip
          path: swEOS_ubuntu
