name: Windows
on: 
  push:
    branches: master
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Library/build
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  PYTHON_PATH: C:/hostedtoolcache/windows/Python/3.8.7/x64
  HOME: D:/a/saltwatereos/saltwatereos
jobs:
  buildApp:
    name: library
    runs-on: windows-latest
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # config msbuild
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      # install Qt5
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          dir: '${{ github.workspace }}/QT/'

      # install dependencies, e.g. VTK, swig
      - name: install dependencies
        working-directory: ${HOME}
        run: |
          git clone https://github.com/zguoch/dependencies_swEOS.git
          cd dependencies_swEOS
          unzip -qq swigwin-4.0.2.zip
          unzip -qq VTK8.2.zip

      # build swEOS library
      - name: compile library
        working-directory: ${HOME}
        run: |
          echo "工作目录: " ${{env.GITHUB_WORKSPACE}}
          mkdir Library/build
          cd Library/build
          cmake -DSWIG_EXECUTABLE=${HOME}/dependencies_swEOS/swigwin-4.0.2/swig.exe -DPYTHON_INCLUDE_DIR=${{env.PYTHON_PATH}}/include -DPYTHON_LIBRARY=${{env.PYTHON_PATH}}/libs/python38.lib -DBuild_API_tcl=OFF -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}} -DCMAKE_GENERATOR_PLATFORM=${{env.BUILD_PLATFORM}} .
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} eosH2ONaCl.sln
          mkdir ../API/python/pyswEOS
          cp swig/H2O/H2O.py ../API/python/pyswEOS
          cp swig/H2O/Release/*H2O* ../API/python/pyswEOS
          cp swig/NaCl/NaCl.py ../API/python/pyswEOS
          cp swig/NaCl/Release/*NaCl* ../API/python/pyswEOS
          cp swig/H2ONaCl/H2ONaCl.py ../API/python/pyswEOS
          cp swig/H2ONaCl/Release/*H2ONaCl* ../API/python/pyswEOS
          mkdir Library/lib
          cp Release/*.lib ../lib/

      # build swEOS cmd app
      - name: build cmd app
        working-directory: ${HOME}
        run: |
          mkdir commandline\build
          cd commandline\build
          cmake ..
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} SaltWaterEOS.sln
      
      # build desktop app
      - name: build desktop app
        working-directory: ${HOME}
        run: |
          mkdir desktop/build
          cd desktop/build
          cmake -DCMAKE_GENERATOR_PLATFORM=${{env.BUILD_PLATFORM}} -DVTK_DIR=${HOME}/dependencies_swEOS/VTK8.2/lib/cmake/vtk-8.2 ..
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} SaltWaterEOS.sln
          ../../QT/Qt/5.15.2/msvc2019_64/bin/windeployqt.exe Release/swEOS.exe
          cp ${HOME}/dependencies_swEOS/VTK8.2/bin/*.dll Release

      # package
      - name: package
        working-directory: ${HOME}
        run: |
          mkdir swEOS_windows
          cp -r Library/lib swEOS_windows/
          cp -r Library/API swEOS_windows/
          cp -r Library/include swEOS_windows/
          cp commandline\build\Release\*.exe swEOS_windows\swEOS_cmd.exe
          cp -r desktop\build\Release swEOS_windows\
      
      # debug workflow
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - uses: actions/upload-artifact@v2
        with:
          name: swEOS_windows.zip
          path: swEOS_windows