name: Windows
on: 
  push:
    branches: master
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH_LIB: Library\build
  SOLUTION_FILE_PATH_CMD: commandline\build
  BUILD_CONFIGURATION: Release
jobs:
  buildApp:
    name: library
    runs-on: windows-latest
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH_LIB}}
      - name: cmake library
        run: |
          mkdir Library/build
          cd Library/build
          cmake -DBuild_API_MultiLanguage=OFF ..
      - name: msbuild library
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH_LIB}}\eosH2ONaCl.sln
          mkdir Library\lib
          cp ${{env.SOLUTION_FILE_PATH_LIB}}\Release\*.lib Library\lib
      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH_CMD}}
      - name: cmake command line app
        run: |
          mkdir -p commandline/build
          cd commandline/build
          cmake ..
      - name: msbuild cmd app
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH_CMD}}\SaltWaterEOS.sln
      - name: package
        run: |
          mkdir swEOS_windows
          cp ${{env.SOLUTION_FILE_PATH_LIB}}\Release\*.lib swEOS_windows\
          cp ${{env.SOLUTION_FILE_PATH_CMD}}\Release\..\..\commandline\build\Release\*.exe swEOS_windows\
      - uses: actions/upload-artifact@v2
        with:
          name: swEOS_windows.zip
          path: swEOS_windows
      