name: Windows
on: 
  push:
    branches: master
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Library/build

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
jobs:
  buildApp:
    name: library
    runs-on: windows-latest
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          dir: '${{ github.workspace }}/QT/'
      - name: install dependence
        run: |
          git clone https://github.com/zguoch/independence_swEOS.git
          cd independence_swEOS
          unzip -qq swigwin-4.0.2.zip
          unzip -qq VTK8.2.zip
          pwd
          cd ..
      - name: compile library
        run: |
          mkdir Library/build
          cd Library/build
          cmake -DSWIG_EXECUTABLE=D:/a/saltwatereos/saltwatereos/independence_swEOS/swigwin-4.0.2/swig.exe -DBuild_API_tcl=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 ..
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          dir D:/a/saltwatereos/saltwatereos/Library/build
          echo ${{env.BUILD_CONFIGURATION}}
          echo ${{env.SOLUTION_FILE_PATH}}
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} D:\a\saltwatereos\saltwatereos\Library\build\eosH2ONaCl.sln
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} D:\a\saltwatereos\saltwatereos\Library\build\eosH2ONaCl.sln /t:ALL_BUILD;INSTALL 
      # - name: build command line app
      #   run: |
      #     mkdir -p commandline/build
      #     cd commandline/build
      #     cmake ..
      #     make 
      # - name: package
      #   run: |
      #     mkdir libs_ubuntu
      #     cp -rf Library/lib libs_ubuntu/
      #     cp -rf Library/API libs_ubuntu/
      #     cp -rf Library/include libs_ubuntu/
      #     cp commandline/build/swEOS libs_ubuntu/
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: libs_ubuntu.zip
      #     path: libs_ubuntu